language: php

sudo: false

php:
  - 5.3
  - 5.4

cache:
    - apt

services:
  - mongodb
  - memcached
  - redis-server

before_install:
 - ./unit-tests/ci/install_prereqs.sh
 - ./unit-tests/ci/setup_dbs.sh

before_script:
 - git submodule --quiet update --init --recursive
 - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -Werror -Wno-error=uninitialized"; phpize && ./configure --silent --enable-phalcon && make --silent -j4 > /dev/null && sudo make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini)
 - ulimit -c unlimited || true

script:
 - ZEND_DONT_UNLOAD_MODULES=1 $(phpenv which php) ./unit-tests/ci/phpunit.php --debug -c unit-tests/phpunit.xml

after_failure:
 - ./unit-tests/ci/after_failure.sh

addons:
  apt:
    packages:
      - gdb
      - re2c