language: php

php:
  - 5.4
  - 5.5

sudo: false

env:
  - PHALCON_VERSION="phalcon-v2.0.0"

before_script:
  # install  phalcon/cphalcon
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && make install && phpenv config-add ../unit-tests/ci/phalcon.ini
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - cd ../..

  # run the composer update
  - travis_retry composer self-update
  - travis_retry composer require phpunit/phpunit --prefer-dist
  - travis_retry composer update --prefer-source --no-interaction --prefer-stable

script:
  - chmod a+x ./unit-tests/phpunit.xml
  - phpunit -c ./unit-tests/phpunit.xml