<!--
//@todo add in post data back into fields.
//@todo client side validation
!-->
<script>
    //define our login_tab we are showing either login or register
    var login_tab = '<?php echo (isset($login_tab)) ? $login_tab : "login-form"; ?>'
</script>

<div class="container ">
    <div class="jumbotron">
        <h1>MailGun-Project</h1>

    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Login</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">Register</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <?php echo $this->tag->form(array("login/check", "autocomplete" => "off","id"=>"login-form" , "style" => "display:none")) ?>
                            <div class="form-group">
                                <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" required autofocus value="">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" id="password" tabindex="2" class="form-control" required autofocus placeholder="Password">
                            </div>
                            <div class="form-group text-center">
                                <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                <label for="remember"> Remember Me</label>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-6 col-sm-offset-3">
                                        <button type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login">
                                            Login
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="text-center">
                                            <a href="/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </form>
                            <?php echo $this->tag->form(array("login/register", "autocomplete" => "off","id"=>"register-form", "style" => "display:none")) ?>
                            <div class="form-group">
                                <input type="email" name="email" id="email" tabindex="1" class="form-control" required placeholder="Email Address" value="">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                            </div>
                            <div class="form-group">
                                <input type="password" name="confirm" id="confirm" tabindex="2" class="form-control" placeholder="Confirm Password">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-sm-6 col-sm-offset-3">
                                        <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
                                    </div>
                                </div>
                            </div>
                            </form>

                        </div>

                    </div>
                </div>
            </div>
            <?php echo $this->flash->output(); ?>
        </div>
    </div>

</div>